name: Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    name: Build & Test
    runs-on: ubuntu-latest
    container:
      image: node:21
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Set up Git
        run: |
          git config --global init.defaultBranch main
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git config --global --add safe.directory /__w/break-check/break-check

      - name: Environment Info
        run: |
          pwd
          ls -al
          git status
          node -v
          npm -v

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Break Check
        uses: ./
        with:
          pattern: "node_test.go"
          testCmd: "go test -v ./..."
